version: "0.2"
services:
  planingproyectucc-backend:
    type: web
    routes:
      - path: /           # ruta raíz
        port: 8080
        protocol: HTTP
        public: true
      - path: /login      # ruta de login
        port: 8080
        protocol: HTTP
        public: true
      - path: /dashboard  # ruta de dashboard
        port: 8080
        protocol: HTTP
        public: true
    source:
      type: git
      # URL de tu repositorio y rama principal
      url: "https://github.com/miusarname2/PlaningProyectUcc.git"
      branch: main
    build:
      type: buildpacks
      # Builder genérico que incluye soporte para PHP 8.x
      builder: "gcr.io/buildpacks/builder:v1"
      # Opcional: puedes especificar buildpacks concretos
      # buildpacks:
      #   - "heroku/php"
    resources:
      cpu: 0.1         # 0.1 vCPU
      memory: 512MB    # 512 MB de RAM
      disk: 512MB      # 512 MB de disco
    env:
      # Puerto en que Laravel servirá la aplicación
      - name: PORT
        value: "8080"
      # Limite de memoria para Composer durante el build
      - name: COMPOSER_MEMORY_LIMIT
        value: "-1"
      # Variables de entorno propias de Laravel
      - name: APP_ENV
        value: "local"
      - name: APP_DEBUG
        value: "false"
      - name: APP_KEY
        # Genera tu APP_KEY con `php artisan key:generate --show`
        value: "base64:REEMPLAZA_CON_TU_APP_KEY"
      # Ejemplo de variables para conexión a base de datos
      - name: DB_CONNECTION
        value: "mysql"
      - name: DB_HOST
        value: "tu-host-db"
      - name: DB_PORT
        value: "3306"
      - name: DB_DATABASE
        value: "tu_base_datos"
      - name: DB_USERNAME
        value: "tu_usuario"
      - name: DB_PASSWORD
        value: "tu_contraseña"
    ports:
      - port: 8080
